### PR TITLE
Use python plistlib instead of a bundled version

### PR DESCRIPTION
**Pull request by jamesgk**

### CODE REVIEW

**Comment by typesupply** [comment]
There are legacy reasons for using the bundled version. (Short version, the bundled version predates the standardlib version, older FontLabs can't use Python with plistlib in the standardlib). I don't have an opinion on if those reasons are still strong enough to justify the bundled version.

Are there any issues that you are experiencing with using the bundled version? Or, is this a general cleanup change?

**Comment by jamesgk** [comment]
It was just a cleanup change following https://github.com/googlei18n/fontmake/issues/31#issuecomment-186124801 (cc @behdad). Since it doesn't even fix the issue from that thread, I don't really mind either way myself.

**Comment by twardoch** [comment]
There is the https://pypi.python.org/pypi/unicodedata2 module which is up-to-date with Unicode, while the unicodedata module bundled with Python is always unpredictably outdated. So a decent strategy is: 

```
try: 
  import unicodedata2 as unicodedata
except ImportError: 
  import unicodedata
```

It's a soft dependancy on unicodedata2 with fallback on bundled. 

This could be reversed here, if the bundled plistlib is renamed to plistlib0: 

```
try: 
  import plistlib
except ImportError:,
  import plistlib0 as plistlib
```

Or the bundled plistlib could be moved into a 'legacy' folder and then: 

```
try: 
  import plistlib
except ImportError: 
  import legacy.plistlib as plistlib
```

Not sure if it’s worth the effort, though. I think most FontLab Studio 5.0.x users have updated to 5.1.x/5.2.x which works with Python 2.7.x.

**Comment by twardoch** [comment]
Or, to echo `from __future__ import`, move the bundled plistlib into a folder named `past` and use: 

```
try: 
  import plistlib
except ImportError:
  import past.plistlib as plistlib
```

**Pull request closed without merging**
