### PR TITLE
Fix default file name scheme with case insensitive file systems

### PR DESCRIPTION
**Pull request by djdm**
The current glif default file name scheme assumes that only one character of a glyph name is case sensitive.
This creates clashes between glyph names like 'Lj' and 'LJ' as they are saved as Lj_.glif and LJ_.glif which is the same for HFS+ on OS X. This happens in Robofab, Robofont and Glyphs, one of the two files will be overwritten by the other.
Some tools like vfb2ufo assume more than one character is case sensitive by adding as many underscores as uppercase characters but clashes might still occur in cases like 'AbC' and 'ABc' saved as AbC__.glif and ABc__.glif.

We wrote the test testCaseInsensitiveDefaultFileNameScheme for those cases.
We’ve also modified glifLib.glyphNameToFileName to add an underscore after any uppercase, escape underscore by adding an underscore, and replacing the initial period by an underscore as before.
That way L_j.glif and L_J_.glif, A_bC_.glif and A_B_c.glif or even 'Lj' and 'l_j' saved as L_j.glif and l__j.glif don’t clash.

### CODE REVIEW

**Comment by behdad** [comment]
And here I was naively thinking that maybe I can remove the case-insensitive-filesystem hacks from fonttools some time soon...

**Comment by typesupply** [comment]
Did you look at the UFO 3 naming scheme? http://unifiedfontobject.org/versions/ufo3/conventions.html#usernametofilename

**Comment by moyogo** [comment]
We noticed silnrsi/pysilfont was doing that but we didn't see the UFO 3 naming scheme.
It seemed l__j.glif was better than l_j000000000000001.glif.

So what can we do to have robofab not overwrite files without using the ufo3k branch?

**Comment by adrientetar** [comment]
> which is the same for HFS+ on OS X

Same for NTFS on Windows. cc me

**Comment by anthrotype** [comment]
@typesupply no, we didn't look at the UFO3 naming scheme. Any scheme for me would be good, as long as it prevent any data loss when working with case insensitive file systems.
Actually, I only now realise there's a "filenames" module dealing exactly with this in the "ufo3k" branch:
https://github.com/robofab-developers/robofab/blob/ufo3k/Lib/ufoLib/filenames.py
I believe that support for case insensitive filesystem should be backported to UFO2 and merged in the master branch. The latter is regarded by many as the current "stable" version of robofab, so one would expect that the default glif naming scheme would be safe enough to prevent files from being overwritten because of case insensitivity.
And this is not just robofab. Also Robofont, Glyphs and vfb2ufo all have the same (or similar) problem.

**Comment by typesupply** [comment]
I've been thinking about this. I don't think it would be wise to backport the UFO 3 naming algorithm to RoboFab's master branch. That branch is more or less in maintenance mode and this change would be massive and have far reaching effects. So, I've been reviewing your proposed patch. I'm concerned about things like this:

https://github.com/anthrotype/robofab/commit/48c07f51c24c9736af561f5714bf8b7d13c50e17#diff-82e079890dd04ce4510b349404eda4b8R65

And this:

https://github.com/anthrotype/robofab/commit/48c07f51c24c9736af561f5714bf8b7d13c50e17#diff-e165129df0adcdeb6906a2b3a7d392a2R103

These kinds of glyph names are very common and are in who knows how many UFOs. I'm concerned that GLIFs that have been named one way for a decade will suddenly have new names. RoboFab's glifLib will preserve file names when writing:

https://github.com/robofab-developers/robofab/blob/master/Lib/robofab/glifLib.py#L216

So, as long as that works, GLIFs within a UFO will not be affected. But, in "save as" operations, it may not work as expected. And, in the case of new fonts, GLIFs will have completely different names than before. I'm comfortable with that when jumping UFO format version numbers, but doing it within UFO 2 makes me nervous.

(Yeah, the old naming system sucks. We've replaced it but everything just needs to catch up to UFO 3. Unfortunately there is more desire for that to happen than there are resources to make it happen.)

One thing that might solve this less bluntly would be to implement a glyph name to file name function. @letterror built support for this into RoboFab as a way to work around another file system problem that we had ages ago:

https://github.com/robofab-developers/robofab/blob/master/Lib/robofab/tools/glyphNameSchemes.py

RoboFab knows how to handle these during write operations:

https://github.com/robofab-developers/robofab/blob/master/Lib/robofab/objects/objectsBase.py#L872
https://github.com/robofab-developers/robofab/blob/master/Lib/robofab/glifLib.py#L113

This will let you have your own file name creation function without changing the default behavior. I don't remember exactly how to implement one of those, but maybe Erik does. Anyway, you could add something like that and I'd review it for the RoboFab master branch.

**Comment by anthrotype** [comment]
I see your concerns. I guess it probably makes more sense to implement a new glyph name to file name function, and use that on an optional basis, instead of modifying the default naming scheme for UFO2.
OK, I'll rework the patch and try to place it inside glyphNameSchemes.py module.
Thanks.

**Comment by benkiel** [comment]
@anthrotype OK to close this request?

**Comment by anthrotype** [comment]
Yes sure.

**Pull request closed without merging**
