### PR TITLE
Fix two Python syntax errors

### PR DESCRIPTION
**Pull request by cclauss**
__flake8__ was able to spot three Python syntax errors in the repo and this PR proposes fixes for two of them.

$ __python2 -m flake8 . --count --select=E9 --show-source --statistics__
```
./Tools/installFontLab/installerScript.py:21:25: E999 SyntaxError: invalid syntax
for moduleName, data in %(moduleData)s.items():
                        ^
./Docs/Examples/objects/RGlyph_03.py:12:32: E999 SyntaxError: invalid syntax
        if component.baseGlyph = oldBaseGlyph:
                               ^
./Docs/Examples/howtos/fontlabRemote_03.py:8:1: E999 SyntaxError: trailing comma not allowed without surrounding parentheses
from robofab.tools.remote import transmitGlyph, receiveGlyph,
^
3     E999 SyntaxError: trailing comma not allowed without surrounding parentheses
3
```

For the first syntax error, I believe the solution is to put quotes around __%(moduleData)s__ but the syntax is strange so I did not propose a fix for that one.

A __.travis.yml__ file is included to allow Travis Continuous Integration to do automated testing on all future pull requests.  This file will do nothing unless the user __robofab-developers__ goes to https://travis-ci.org/profile, logs in with GitHub credentials, and flips the repository switch __on__.

### CODE REVIEW

**Comment by benkiel** [comment]
@cclauss Thanks for this. We have declared that we're not updating RoboFab further, we are focusing our attention on FontParts. So, we won't be setting up Travis for RoboFab, but I will cherry pick those two changes.

**Comment by cclauss** [comment]
Understood.  Thank makes sense.  I could not figure out the other syntax error.

**Comment by jackjennings** [comment]
@benkiel it's now possible to "archive" a project on GitHub, making it read-only. Alongside adding a note in the README, maybe archiving would be in line with the above?

**Comment by benkiel** [comment]
@jackjennings Ah! I didn't know that. Line added in the README, but yes, that would be in line. Thanks for the tip

**Pull request merged**
