### PR TITLE
adding new Sphinx-based docs, removing old Documentation folder

### PR DESCRIPTION
**Pull request by gferreira**
cheers!

### CODE REVIEW

**Comment by benkiel** [comment]
Gustavo, so many thanks!

**Comment by LettError** [comment]
Thanks Gustavo!

**Comment by LettError** [comment]
I'm missing something: 

eBookPro:Docs erik$ make html
sphinx-build -b html -d _build/doctrees   source _build/html
Traceback (most recent call last):
  File "/usr/local/bin/sphinx-build", line 8, in <module>
    load_entry_point('Sphinx==1.1.3', 'console_scripts', 'sphinx-build')()
  File "/Library/Python/2.7/site-packages/Sphinx-1.1.3-py2.7.egg/sphinx/__init__.py", line 47, in main
    from sphinx import cmdline
  File "/Library/Python/2.7/site-packages/Sphinx-1.1.3-py2.7.egg/sphinx/cmdline.py", line 18, in <module>
    from docutils.utils import SystemMessage
  File "/Library/Python/2.7/site-packages/docutils-0.9-py2.7.egg/docutils/utils/__init__.py", line 19, in <module>
    from docutils.io import FileOutput
  File "/Library/Python/2.7/site-packages/docutils-0.9-py2.7.egg/docutils/io.py", line 18, in <module>
    from docutils.error_reporting import locale_encoding, ErrorString, ErrorOutput
  File "/Library/Python/2.7/site-packages/docutils-0.9-py2.7.egg/docutils/error_reporting.py", line 47, in <module>
    locale_encoding = locale.getlocale()[1] or locale.getdefaultlocale()[1]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 511, in getdefaultlocale
    return _parse_localename(localename)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 443, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
make: *** [html] Error 1

**Comment by gferreira** [comment]
maybe some configuration settings are not supported in this version of Sphinx (1.1.3) …

can you try upgrading to the latest [1.3.1]? (fingers crossed)

**Comment by LettError** [comment]
- Updated to Spinx 1.3.1, same error.
- Looked up "ValueError: unknown locale: UTF-8" and found: http://stackoverflow.com/questions/19961239/pelican-3-3-pelican-quickstart-error-valueerror-unknown-locale-utf-8
- Added the suggested exports to my .bash_profile and generated again.
- Now it works.

Was my bash profile unusually ancient or badly configured?

**Comment by gferreira** [comment]
great, I'm glad it works now!

(now that you mention, I vaguely remember having to update my bash profile a long time ago… not sure if it was for the same reason)

**Comment by LettError** [comment]
Hi Gustavo, 

- Is the small object map at the top of the page supposed to link somewhere?
It is on every page but does not appear to do anything.



-Perhaps related, is there a way to make the items on /Docs/_build/html/objects/model.html clickable again?

- I don't need the Superpolator / LettError links on every page. The FontTools/TTX link may also not necessary. 

Erik

**Comment by gferreira** [comment]
hi Erik,

- the small object map now links to the big object map
- the second group of external links in the sidebar has been removed

I also removed some extra files which were not necessary: the RF docs extension, which was included by mistake, and some theme leftovers.

I've just submitted another pull request with those changes. 

the big object map should be clickable: the SVG does have links, as well as hover states (this part was done by @casasin). but for some reason Sphinx is disabling it, so I had to add the text links underneath it. I'll give it another try soon and see if it can be fixed.

**Pull request merged**
